[package]
name = "inlet"
version = "0.1.0"
edition = "2021"

[profile.dev]
debug = true

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
serde = { version = "1.0.209", features = ["derive"] }
toml = "0.8.19"
